#!/usr/bin/env python

import os
import hashlib
import shutil

#  Move files in from_dir to to_dir if they don't already exist,
#  otherwise delete them.

def md5(filename):
    hash_md5 = hashlib.md5()
    with open(filename, "rb") as f:
        for chunk in iter(lambda: f.read(2 ** 20), b""):
            hash_md5.update(chunk)
    return hash_md5.hexdigest()

if __name__ == "__main__":

	from_dir = os.path.join(os.path.expanduser('~'), 'Downloads')
	to_dir = os.path.join(os.path.expanduser('~'), 'Pictures/Chromecast Home')

	hashlist = {}
	print 'Calculating hashes for all files in {}'.format(to_dir)
	for dirpath, dirnames, filenames in os.walk(to_dir):
		for filename in filenames:
			fn = os.path.join(dirpath, filename)
			hashlist[md5(fn)] = fn
				
	ctr = 0
	for dirpath, dirnames, filenames in os.walk(from_dir):
		for filename in filenames:
			if filename.endswith('.jpg'):
				fn = os.path.join(dirpath, filename)
				md5_hash = md5(fn)
				if hashlist.has_key(md5_hash):
					print '{} duplicates {}'.format(fn, hashlist[md5_hash])
					os.unlink(fn)
				else:
					print 'Storing {}'.format(fn)
					shutil.move(fn, os.path.join(to_dir, filename))
					hashlist[md5_hash] = os.path.join(to_dir, filename)
					ctr = ctr + 1

	print 'Stored {} new files'.format(ctr)
